bucket:
  persistence: workshop-data-lake-persistence
  client:
    # regex pattern
    pattern: workshop-data-lake-client-(\d+)
    # regex pattern
    valid_file: .*/.*.csv
database:
  credential_name: BUCKET_CLIENT_1
